name: sculptor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - h5py
  - pytables
  - pyqt
  - astropy
  - matplotlib
  - numpy
  - pandas
  - scipy
  - pip
  - pip:
      - corner
      - lmfit
      - emcee
      - extinction
      - spectres
      - linetools
      - ipykernel
      - sphinx
      - nbsphinx
      - nbsphinx-link
      - PyYAML
      - tqdm
      - importlib_resources

