# run: conda env create --file environment.yml
name: sculptor
channels:
- conda-forge
- defaults
dependencies:
- astropy>=4.0.2
- matplotlib>=3.3.1
- numpy>=1.19.1
- pandas>=1.1.3
- pip>=20.3.3
- pyqt>=5.9.2
- python>=3.8.5
- scipy>=1.5.0
- pytables>=3.6.1
- emcee>=3.0.0
- extinction >=0.4.5
- pyyaml >= 5.4.1
- tqdm >= 4.6.0
- h5py
- sphinx>=1.4
- ipykernel
- pip:
  - lmfit>=1.0.1
  - corner>=2.1.0
  - spectres
  - nbsphinx
  - nbsphinx-link
  - linetools
